window.EVENTS = {
    "dates": [
        "5/1/2026",
        "4/1/2026",
        "3/1/2026",
        "2/1/2026",
        "1/1/2026",
        "1/1/2026",
        "1/1/2026",
        "6/2/2026",
        "6/2/2026",
        "6/2/2026",
        "7/5/2026",
        "7/5/2026",
        "7/5/2026"
    ],
    "events": [
        "2500lb shotput",
        "Octuple jump",
        "1m hurdles",
        "Long jump",
        "10000m sprint",
        "10000m sprint",
        "10000m sprint",
        "Pookalam",
        "Pookalam",
        "Pookalam",
        "Football",
        "Football",
        "Football"
    ],
    "category": [
        "E",
        "B",
        "F",
        "D",
        "A",
        "A",
        "A",
        "All House",
        "All House",
        "All House",
        "MS",
        "MS",
        "MS"
    ],
    "gender": [
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "",
        "",
        "",
        "Boys",
        "Boys",
        "Boys"
    ],
    "houses": [
        "Joy",
        "Peace",
        "Faith",
        "Hope",
        "Joy",
        "Peace",
        "Faith",
        "Joy",
        "Peace",
        "Faith",
        "Faith",
        "Peace",
        "Joy"
    ],
    "points": [
        5,
        12,
        10,
        10,
        15,
        5,
        10,
        25,
        15,
        10,
        15,
        10,
        5
    ],
    "places": [
        "3rd",
        "1st",
        "3rd",
        "2nd",
        "1st",
        "3rd",
        "2nd",
        "1st",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "3rd"
    ],
    "types": [
        "March-past",
        "Field",
        "Field",
        "Field",
        "Track",
        "Track",
        "Track",
        "Culture",
        "Culture",
        "Culture",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports"
    ]
};
