window.EVENTS = {
    "dates": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "events": [
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Throwball",
        "Throwball",
        "Throwball",
        "Throwball"
    ],
    "category": [
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "MS",
        "MS",
        "MS",
        "MS",
        "HS",
        "HS",
        "HS",
        "HS",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "MS",
        "MS",
        "MS",
        "MS",
        "HS",
        "HS",
        "HS",
        "HS",
        "ES",
        "ES",
        "ES",
        "ES",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS"
    ],
    "gender": [
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed"
    ],
    "houses": [
        "Joy",
        "Hope",
        "Faith",
        "Peace",
        "Hope",
        "Faith",
        "Joy",
        "Peace",
        "Faith",
        "Hope",
        "Peace",
        "Joy",
        "Faith",
        "Peace",
        "Hope",
        "Joy",
        "Joy",
        "Hope",
        "Faith",
        "Peace",
        "Joy",
        "Faith",
        "Hope",
        "Peace",
        "Faith",
        "Peace",
        "Joy",
        "Hope",
        "Peace",
        "Hope",
        "Joy",
        "Faith",
        "Joy",
        "Faith",
        "Hope",
        "Peace",
        "Peace",
        "Joy",
        "Hope",
        "Faith",
        "Hope",
        "Faith",
        "Joy",
        "Peace"
    ],
    "points": [
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20
    ],
    "places": [
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th"
    ],
    "types": [
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports"
    ]
};
