window.EVENTS = {
    "dates": [
<<<<<<< Updated upstream
        "5/1/2026",
        "4/1/2026",
        "3/1/2026",
        "2/1/2026",
        "1/1/2026",
        "1/1/2026",
        "1/1/2026",
        "6/2/2026",
        "6/2/2026",
        "6/2/2026",
        "7/5/2026",
        "7/5/2026",
        "7/5/2026"
=======
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
>>>>>>> Stashed changes
    ],
    "events": [
        "2500lb shotput",
        "Octuple jump",
        "1m hurdles",
        "Long jump",
        "10000m sprint",
        "10000m sprint",
        "10000m sprint",
        "Pookalam",
        "Pookalam",
        "Pookalam",
        "Football",
        "Football",
<<<<<<< Updated upstream
        "Football"
=======
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Football",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Cricket",
        "Throwball",
        "Throwball",
        "Throwball",
        "Throwball"
>>>>>>> Stashed changes
    ],
    "category": [
        "E",
        "B",
        "F",
        "D",
        "A",
        "A",
        "A",
        "All House",
        "All House",
        "All House",
        "MS",
        "MS",
<<<<<<< Updated upstream
        "MS"
=======
        "MS",
        "MS",
        "HS",
        "HS",
        "HS",
        "HS",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "ES",
        "MS",
        "MS",
        "MS",
        "MS",
        "HS",
        "HS",
        "HS",
        "HS",
        "ES",
        "ES",
        "ES",
        "ES",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS",
        "MS/HS"
>>>>>>> Stashed changes
    ],
    "gender": [
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "",
        "",
        "",
        "Boys",
        "Boys",
<<<<<<< Updated upstream
        "Boys"
=======
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed"
>>>>>>> Stashed changes
    ],
    "houses": [
        "Joy",
        "Peace",
        "Faith",
        "Hope",
        "Joy",
        "Peace",
        "Faith",
        "Joy",
        "Peace",
        "Faith",
        "Faith",
        "Peace",
<<<<<<< Updated upstream
        "Joy"
    ],
    "points": [
        5,
        12,
        10,
        10,
        15,
        5,
        10,
        25,
        15,
        10,
        15,
        10,
        5
=======
        "Hope",
        "Joy",
        "Joy",
        "Hope",
        "Faith",
        "Peace",
        "Joy",
        "Faith",
        "Hope",
        "Peace",
        "Faith",
        "Peace",
        "Joy",
        "Hope",
        "Peace",
        "Hope",
        "Joy",
        "Faith",
        "Joy",
        "Faith",
        "Hope",
        "Peace",
        "Peace",
        "Joy",
        "Hope",
        "Faith",
        "Hope",
        "Faith",
        "Joy",
        "Peace"
    ],
    "points": [
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20,
        50,
        40,
        30,
        20
>>>>>>> Stashed changes
    ],
    "places": [
        "3rd",
        "1st",
        "3rd",
        "2nd",
        "1st",
        "3rd",
        "2nd",
        "1st",
        "2nd",
        "3rd",
        "1st",
        "2nd",
<<<<<<< Updated upstream
        "3rd"
=======
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th",
        "1st",
        "2nd",
        "3rd",
        "4th"
>>>>>>> Stashed changes
    ],
    "types": [
        "March-past",
        "Field",
        "Field",
        "Field",
        "Track",
        "Track",
        "Track",
        "Culture",
        "Culture",
        "Culture",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports",
        "General/Team Sports"
    ]
};
