window.EVENTS ={
    "dates": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "events": [
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Football",
        "Football",
        "Football",
        "Football",
        "Cricket",
        "Cricket",
        "Throwball",
        "25m Freestyle",
        "25m Freestyle",
        "25m Breaststroke",
        "25m Breaststroke",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Butterfly",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Freestyle",
        "25m Butterfly",
        "25m Freestyle",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Freestyle",
        "25m Freestyle",
        "25m Freestyle",
        "25m Freestyle",
        "80m Hurdles",
        "80m Hurdles",
        "80m Hurdles",
        "80m Hurdles",
        "80m Hurdles",
        "Discus",
        "Discus",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "200m",
        "200m",
        "200m",
        "200m",
        "400m",
        "400m",
        "400m",
        "Table Tennis",
        "Table Tennis",
        "Table Tennis",
        "Badminton",
        "Badminton",
        "Badminton",
        "Badminton",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "100m",
        "100m",
        "100m",
        "100m",
        "100m",
        "100m",
        "Relay",
        "Relay",
        "Relay",
        "Tug of War",
        "8x100m Relay",
        "Drill",
        "Deco",
        "March Past"
    ],
    "category": [
        "ES",
        "ES",
        "MS",
        "HS",
        "ES",
        "ES",
        "MS",
        "HS",
        "ES",
        "MS/HS",
        "MS/HS",
        "A",
        "A",
        "A",
        "A",
        "A",
        "A",
        "A",
        "B",
        "B",
        "B",
        "B",
        "C",
        "C",
        "C",
        "C",
        "C",
        "D",
        "D",
        "D",
        "D",
        "E",
        "F",
        "F",
        "A",
        "B",
        "A",
        "A",
        "B",
        "B",
        "C",
        "C",
        "D",
        "E",
        "F",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "E",
        "F",
        "F",
        "F",
        "F",
        "A",
        "A",
        "A",
        "B",
        "B",
        "C",
        "C",
        "C",
        "E",
        "F",
        "A",
        "C",
        "C",
        "D",
        "A",
        "C",
        "C",
        "MS",
        "HS",
        "HS",
        "ES",
        "ES",
        "MS",
        "HS",
        "PP Group A",
        "PP Group A",
        "LKG Group A",
        "LKG Group B",
        "LKG Group B",
        "UKG Group C",
        "UKG Group A",
        "UKG Group B",
        "UKG Group B",
        "UKG Group C",
        "G1 Group A",
        "G1 Group A",
        "G1 Group B",
        "G1 Group A",
        "G1 Group A",
        "G2 Group A",
        "G2 Group A",
        "G2 Group B",
        "G2 Group C",
        "G2 Group C",
        "G2 Group A",
        "G2 Group B",
        "G2 Group B",
        "G3 Group A",
        "G3 Group A",
        "G3 Group A",
        "G3 Group C",
        "G3 Group A",
        "G3 Group B",
        "G3 Group B",
        "G3 Group C",
        "G3 Group D",
        "C",
        "C",
        "D",
        "E",
        "F",
        "F",
        "Grade 1",
        "Grade 2",
        "Grade 3",
        "All House",
        "HS",
        "All House",
        "All House",
        "All House"
    ],
    "gender": [
        "Girls",
        "Boys",
        "Mixed",
        "Mixed",
        "Boys",
        "Girls",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed"
    ],
    "points": [
        40,
        50,
        60,
        45,
        40,
        30,
        30,
        60,
        30,
        45,
        50,
        10,
        10,
        10,
        5,
        15,
        10,
        10,
        5,
        15,
        10,
        10,
        5,
        5,
        5,
        10,
        5,
        15,
        10,
        15,
        10,
        5,
        5,
        5,
        15,
        15,
        15,
        15,
        15,
        5,
        15,
        15,
        5,
        10,
        15,
        15,
        10,
        5,
        5,
        10,
        5,
        15,
        15,
        15,
        10,
        10,
        5,
        15,
        10,
        5,
        5,
        10,
        10,
        5,
        15,
        15,
        5,
        5,
        10,
        5,
        15,
        5,
        15,
        10,
        10,
        15,
        5,
        10,
        15,
        15,
        5,
        15,
        5,
        15,
        10,
        5,
        15,
        10,
        10,
        5,
        5,
        10,
        5,
        10,
        10,
        5,
        10,
        5,
        10,
        15,
        5,
        15,
        15,
        5,
        15,
        10,
        5,
        5,
        5,
        15,
        10,
        5,
        10,
        5,
        5,
        5,
        5,
        15,
        10,
        20,
        20,
        30,
        40,
        30,
        40,
        39,
        44
    ],
    "places": [
        "2nd",
        "1st",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "4th",
        "2nd",
        "3rd",
        "3rd",
        "1st",
        "2nd",
        "2nd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "2nd",
        "3rd",
        "3rd",
        "3rd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "1st",
        "2nd",
        "3rd",
        "3rd",
        "3rd",
        "1st",
        "1st",
        "1st",
        "1st",
        "1st",
        "3rd",
        "1st",
        "1st",
        "3rd",
        "2nd",
        "1st",
        "1st",
        "2nd",
        "3rd",
        "3rd",
        "2nd",
        "3rd",
        "1st",
        "1st",
        "1st",
        "2nd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "3rd",
        "2nd",
        "2nd",
        "3rd",
        "1st",
        "1st",
        "3rd",
        "3rd",
        "2nd",
        "3rd",
        "1st",
        "3rd",
        "1st",
        "2nd",
        "2nd",
        "1st",
        "3rd",
        "2nd",
        "1st",
        "1st",
        "3rd",
        "1st",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "2nd",
        "3rd",
        "3rd",
        "2nd",
        "3rd",
        "2nd",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "2nd",
        "1st",
        "3rd",
        "1st",
        "1st",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "3rd",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "3rd",
        "3rd",
        "3rd",
        "1st",
        "2nd",
        "2nd",
        "2nd",
        "1st",
        "2nd",
        "4th",
        "2nd",
        "4th",
        "3rd"
    ],
    "types": [
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Sports",
        "Track",
        "Drill",
        "Deco",
        "March Past"
    ]
};
