window.EVENTS ={
    "dates": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "events": [
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Football",
        "Football",
        "Football",
        "Football",
        "Cricket",
        "Cricket",
        "Throwball",
        "25m Freestyle",
        "25m Freestyle",
        "25m Freestyle",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Butterfly",
        "25m Backstroke",
        "25m Freestyle",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Freestyle",
        "25m Backstroke",
        "25m Backstroke",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Breaststroke",
        "25m Butterfly",
        "25m Butterfly",
        "25m Butterfly",
        "25m Freestyle",
        "25m Freestyle",
        "25m Backstroke",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Breaststroke",
        "25m Freestyle",
        "25m Freestyle",
        "25m Freestyle",
        "80m Hurdles",
        "80m Hurdles",
        "80m Hurdles",
        "80m Hurdles",
        "Discus",
        "Discus",
        "Discus",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "200m",
        "200m",
        "200m",
        "200m",
        "200m",
        "200m",
        "400m",
        "400m",
        "400m",
        "400m",
        "Table Tennis",
        "Table Tennis",
        "Badminton",
        "Badminton",
        "Badminton",
        "Badminton",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "Flat Race",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "75m",
        "100m",
        "100m",
        "100m",
        "100m",
        "100m",
        "100m",
        "100m",
        "100m",
        "100m",
        "Relay",
        "Relay",
        "Relay",
        "Tug of War",
        "8x100m Relay",
        "Drill",
        "Deco",
        "March Past"
    ],
    "category": [
        "ES",
        "ES",
        "MS",
        "HS",
        "ES",
        "ES",
        "MS",
        "HS",
        "ES",
        "MS/HS",
        "MS/HS",
        "A",
        "A",
        "A",
        "A",
        "A",
        "A",
        "A",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "D",
        "D",
        "D",
        "D",
        "D",
        "D",
        "E",
        "F",
        "F",
        "D",
        "D",
        "F",
        "F",
        "A",
        "A",
        "B",
        "A",
        "B",
        "C",
        "D",
        "D",
        "E",
        "A",
        "D",
        "D",
        "E",
        "F",
        "A",
        "D",
        "D",
        "E",
        "F",
        "F",
        "A",
        "A",
        "B",
        "C",
        "D",
        "D",
        "A",
        "A",
        "B",
        "C",
        "MS",
        "HS",
        "ES",
        "MS",
        "HS",
        "HS",
        "PP Group A",
        "PP Group A",
        "PP Group B",
        "LKG Group A",
        "LKG Group A",
        "LKG Group B",
        "LKG Group B",
        "LKG Group A",
        "LKG Group C",
        "LKG Group D",
        "UKG Group A",
        "UKG Group B",
        "UKG Group A",
        "G1 Group A",
        "G1 Group B",
        "G1 Group B",
        "G1 Group B",
        "G1 Group C",
        "G2 Group A",
        "G2 Group B",
        "G2 Group C",
        "G2 Group C",
        "G3 Group C",
        "G3 Group A",
        "G3 Group C",
        "G3 Group D",
        "G3 Group D",
        "A",
        "A",
        "B",
        "C",
        "D",
        "D",
        "D",
        "F",
        "F",
        "Grade 1",
        "Grade 2",
        "Grade 3",
        "All House",
        "HS",
        "All House",
        "All House",
        "All House"
    ],
    "gender": [
        "Girls",
        "Boys",
        "Mixed",
        "Mixed",
        "Boys",
        "Girls",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed"
    ],
    "points": [
        20,
        20,
        45,
        60,
        20,
        20,
        60,
        75,
        20,
        75,
        20,
        5,
        15,
        5,
        5,
        5,
        5,
        10,
        10,
        10,
        10,
        15,
        15,
        10,
        5,
        10,
        5,
        15,
        10,
        5,
        10,
        5,
        10,
        5,
        10,
        5,
        5,
        15,
        5,
        10,
        5,
        15,
        15,
        5,
        5,
        5,
        5,
        10,
        10,
        5,
        15,
        10,
        5,
        15,
        10,
        5,
        15,
        5,
        15,
        15,
        10,
        10,
        15,
        10,
        5,
        10,
        15,
        15,
        5,
        10,
        5,
        10,
        5,
        15,
        5,
        5,
        5,
        5,
        15,
        10,
        10,
        5,
        15,
        10,
        10,
        5,
        10,
        15,
        10,
        15,
        15,
        15,
        15,
        5,
        15,
        10,
        15,
        5,
        10,
        15,
        5,
        10,
        15,
        15,
        15,
        5,
        15,
        5,
        10,
        10,
        15,
        10,
        15,
        5,
        15,
        15,
        10,
        20,
        30,
        45,
        41,
        42,
        48
    ],
    "places": [
        "4th",
        "4th",
        "3rd",
        "2nd",
        "4th",
        "4th",
        "2nd",
        "1st",
        "4th",
        "1st",
        "4th",
        "3rd",
        "1st",
        "3rd",
        "3rd",
        "3rd",
        "3rd",
        "2nd",
        "2nd",
        "2nd",
        "2nd",
        "1st",
        "1st",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "3rd",
        "1st",
        "3rd",
        "2nd",
        "3rd",
        "1st",
        "1st",
        "3rd",
        "3rd",
        "3rd",
        "3rd",
        "2nd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "1st",
        "3rd",
        "1st",
        "1st",
        "2nd",
        "2nd",
        "1st",
        "2nd",
        "3rd",
        "2nd",
        "1st",
        "1st",
        "3rd",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "1st",
        "3rd",
        "3rd",
        "3rd",
        "3rd",
        "1st",
        "2nd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "2nd",
        "3rd",
        "2nd",
        "1st",
        "2nd",
        "1st",
        "1st",
        "1st",
        "1st",
        "3rd",
        "1st",
        "2nd",
        "1st",
        "3rd",
        "2nd",
        "1st",
        "3rd",
        "2nd",
        "1st",
        "1st",
        "1st",
        "3rd",
        "1st",
        "3rd",
        "2nd",
        "2nd",
        "1st",
        "2nd",
        "1st",
        "3rd",
        "1st",
        "3rd",
        "4th",
        "2nd",
        "3rd",
        "3rd",
        "1st",
        "1st",
        "1st"
    ],
    "types": [
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Track",
        "Track",
        "Track",
        "Track",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Sports",
        "Track",
        "Drill",
        "Deco",
        "March Past"
    ]
};
