window.EVENTS ={
    "dates": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "events": [
        "Basketball",
        "Basketball",
        "Basketball",
        "Basketball",
        "Football",
        "Football",
        "Football",
        "Football",
        "Cricket",
        "Cricket",
        "Throwball",
        "25m Freestyle",
        "25m Freestyle",
        "25m Freestyle",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Butterfly",
        "25m Backstroke",
        "25m Freestyle",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Freestyle",
        "25m Backstroke",
        "25m Backstroke",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Breaststroke",
        "25m Butterfly",
        "25m Butterfly",
        "25m Butterfly",
        "25m Freestyle",
        "25m Freestyle",
        "25m Backstroke",
        "25m Backstroke",
        "25m Breaststroke",
        "25m Breaststroke",
        "25m Freestyle",
        "25m Freestyle",
        "25m Freestyle",
        "80m Hurdles",
        "80m Hurdles",
        "80m Hurdles",
        "80m Hurdles",
        "Discus",
        "Discus",
        "Discus",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "Shot Put",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "High Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "Long Jump",
        "200m",
        "200m",
        "200m",
        "200m",
        "200m",
        "200m",
        "400m",
        "400m",
        "400m",
        "400m"
    ],
    "category": [
        "ES",
        "ES",
        "MS",
        "HS",
        "ES",
        "ES",
        "MS",
        "HS",
        "ES",
        "MS/HS",
        "MS/HS",
        "A",
        "A",
        "A",
        "A",
        "A",
        "A",
        "A",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "C",
        "D",
        "D",
        "D",
        "D",
        "D",
        "D",
        "E",
        "F",
        "F",
        "D",
        "D",
        "F",
        "F",
        "A",
        "A",
        "B",
        "A",
        "B",
        "C",
        "D",
        "D",
        "E",
        "A",
        "D",
        "D",
        "E",
        "F",
        "A",
        "D",
        "D",
        "E",
        "F",
        "F",
        "A",
        "A",
        "B",
        "C",
        "D",
        "D",
        "A",
        "A",
        "B",
        "C"
    ],
    "gender": [
        "Girls",
        "Boys",
        "Mixed",
        "Mixed",
        "Boys",
        "Girls",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Mixed",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Girls",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Girls",
        "Boys",
        "Boys",
        "Boys",
        "Girls",
        "Boys",
        "Girls"
    ],
    "points": [
        20,
        20,
        45,
        60,
        20,
        20,
        60,
        75,
        20,
        75,
        20,
        5,
        15,
        5,
        5,
        5,
        5,
        10,
        10,
        10,
        10,
        15,
        15,
        10,
        5,
        10,
        5,
        15,
        10,
        5,
        10,
        5,
        10,
        5,
        10,
        5,
        5,
        15,
        5,
        10,
        5,
        15,
        15,
        5,
        5,
        5,
        5,
        10,
        10,
        5,
        15,
        10,
        5,
        15,
        10,
        5,
        15,
        5,
        15,
        15,
        10,
        10,
        15,
        10,
        5,
        10,
        15,
        15,
        5,
        10,
        5,
        10,
        5
    ],
    "places": [
        "4th",
        "4th",
        "3rd",
        "2nd",
        "4th",
        "4th",
        "2nd",
        "1st",
        "4th",
        "1st",
        "4th",
        "3rd",
        "1st",
        "3rd",
        "3rd",
        "3rd",
        "3rd",
        "2nd",
        "2nd",
        "2nd",
        "2nd",
        "1st",
        "1st",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "2nd",
        "3rd",
        "3rd",
        "1st",
        "3rd",
        "2nd",
        "3rd",
        "1st",
        "1st",
        "3rd",
        "3rd",
        "3rd",
        "3rd",
        "2nd",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "1st",
        "2nd",
        "3rd",
        "1st",
        "3rd",
        "1st",
        "1st",
        "2nd",
        "2nd",
        "1st",
        "2nd",
        "3rd",
        "2nd",
        "1st",
        "1st",
        "3rd",
        "2nd",
        "3rd",
        "2nd",
        "3rd"
    ],
    "types": [
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Sports",
        "Track",
        "Track",
        "Track",
        "Track",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Field",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track",
        "Track"
    ]
};
